// Structured content model. A lesson is a sequence of typed steps (concept /
// problem), never an HTML blob. Every object here is plain JSON-serializable
// data, so lessons can be authored by hand now and generated by AI later.

/**
 * A weight on the scale: a 1-unit block, or a labeled "mystery" block (a
 * variable). `locked` blocks are part of the given problem and cannot be moved
 * or removed by the learner (rendered in a distinct, muted color).
 */
export type Item =
  | { kind: "unit"; locked?: boolean }
  | { kind: "var"; label: string; weight: number; locked?: boolean };

/** The two pans of the balance scale. */
export interface ScaleState {
  left: Item[];
  right: Item[];
}

/** Scale-based mechanics the learner uses on a problem. */
export type ScaleInteraction =
  | "drag-balance" // drag unit blocks onto a pan until it levels
  | "choose-number" // tap the number a mystery block weighs
  | "remove-both-sides" // remove equal amounts from both pans
  | "split-both-sides" // split both pans into equal groups
  | "solve-equation"; // combine remove + split to isolate the variable

/** Every UI mechanic, including the coordinate-grid graphing one. */
export type Interaction = ScaleInteraction | "match-line";

/** Pure logic that decides correctness, decoupled from the UI mechanic. */
export type ValidatorConfig =
  | { kind: "sides-equal" }
  | { kind: "choose-number"; answer: number }
  | { kind: "isolate-variable" }
  | { kind: "match-line" };

/** Hand-written, misconception-aware feedback. */
export interface Feedback {
  /** Shown on a correct answer (also where deeper understanding forms). */
  correct: string;
  /** Keyed by mistake code returned by the validator. */
  byMistake?: Record<string, string>;
  /** Fallback when no specific mistake matched. */
  default: string;
}

export interface ConceptStep {
  type: "concept";
  title?: string;
  body: string;
  /** Optional illustrative (non-interactive) scale to anchor the idea. */
  scale?: ScaleState;
}

/** Fields shared by every interactive problem. */
interface ProblemBase {
  type: "problem";
  prompt: string;
  feedback: Feedback;
  /** Optional scaffolding for repeated misses (the "Sam" persona). */
  hint?: string;
  /** Show the hint after this many wrong attempts (default 2). */
  hintAfterAttempts?: number;
}

/** A problem solved on the balance scale. */
export interface ScaleProblemStep extends ProblemBase {
  interaction: ScaleInteraction;
  /** Starting configuration of the scale. */
  initial: ScaleState;
  /** Blocks available to drag in (drag-balance). */
  tray?: Item[];
  /** Options for a choose-number problem. */
  choices?: number[];
  /** Allow removing variable blocks too (variables on both sides). */
  removableVars?: boolean;
  validator: ValidatorConfig;
}

/** A problem solved on the coordinate grid: match a target line y = mx + b. */
export interface GraphProblemStep extends ProblemBase {
  interaction: "match-line";
  /** The line the learner must reproduce. */
  target: { m: number; b: number };
  /** Inclusive slider ranges for slope and intercept. */
  mRange: [number, number];
  bRange: [number, number];
  /** Slider step size for both sliders (default 1). */
  sliderStep?: number;
  /** Per-axis step overrides (e.g. mStep 0.5 for a 1/2 slope). */
  mStep?: number;
  bStep?: number;
  validator: { kind: "match-line" };
}

export type ProblemStep = ScaleProblemStep | GraphProblemStep;

export type Step = ConceptStep | ProblemStep;

export interface Lesson {
  id: string;
  title: string;
  /** Short "See it / Keep it / Use it" style tag for the course path. */
  tag: string;
  subtitle: string;
  steps: Step[];
}

export interface LessonMeta {
  id: string;
  title: string;
  tag: string;
  subtitle: string;
}
