// Structured content model. A lesson is a sequence of typed steps (concept /
// problem), never an HTML blob. Every object here is plain JSON-serializable
// data, so lessons can be authored by hand now and generated by AI later.

/**
 * A weight on the scale: a 1-unit block, or a labeled "mystery" block (a
 * variable). `locked` blocks are part of the given problem and cannot be moved
 * or removed by the learner (rendered in a distinct, muted color).
 */
export type Item =
  | { kind: "unit"; locked?: boolean }
  | { kind: "var"; label: string; weight: number; locked?: boolean };

/** The two pans of the balance scale. */
export interface ScaleState {
  left: Item[];
  right: Item[];
}

/** UI mechanic the learner uses on a problem. */
export type Interaction =
  | "drag-balance" // drag unit blocks onto a pan until it levels
  | "choose-number" // tap the number a mystery block weighs
  | "remove-both-sides" // remove equal amounts from both pans
  | "split-both-sides" // split both pans into equal groups
  | "solve-equation"; // combine remove + split to isolate the variable

/** Pure logic that decides correctness, decoupled from the UI mechanic. */
export type ValidatorConfig =
  | { kind: "sides-equal" }
  | { kind: "choose-number"; answer: number }
  | { kind: "isolate-variable" };

/** Hand-written, misconception-aware feedback. */
export interface Feedback {
  /** Shown on a correct answer (also where deeper understanding forms). */
  correct: string;
  /** Keyed by mistake code returned by the validator. */
  byMistake?: Record<string, string>;
  /** Fallback when no specific mistake matched. */
  default: string;
}

export interface ConceptStep {
  type: "concept";
  title?: string;
  body: string;
  /** Optional illustrative (non-interactive) scale to anchor the idea. */
  scale?: ScaleState;
}

export interface ProblemStep {
  type: "problem";
  prompt: string;
  interaction: Interaction;
  /** Starting configuration of the scale. */
  initial: ScaleState;
  /** Blocks available to drag in (drag-balance). */
  tray?: Item[];
  /** Options for a choose-number problem. */
  choices?: number[];
  validator: ValidatorConfig;
  feedback: Feedback;
  /** Optional scaffolding for repeated misses (the "Sam" persona). */
  hint?: string;
  /** Show the hint after this many wrong attempts (default 2). */
  hintAfterAttempts?: number;
  /**
   * Optional easier, scaffolded sub-problem offered after repeated misses.
   * Solving it returns the learner to this (main) problem to try again.
   */
  easier?: ProblemStep;
  /** Offer the easier step after this many wrong attempts (default 2). */
  easierAfterAttempts?: number;
}

export type Step = ConceptStep | ProblemStep;

export interface Lesson {
  id: string;
  title: string;
  /** Short "See it / Keep it / Use it" style tag for the course path. */
  tag: string;
  subtitle: string;
  steps: Step[];
}

export interface LessonMeta {
  id: string;
  title: string;
  tag: string;
  subtitle: string;
}
